// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
import HTTPTypes
public struct Client: APIProtocol {
    /// The underlying HTTP client.
    private let client: UniversalClient
    /// Creates a new client.
    /// - Parameters:
    ///   - serverURL: The server URL that the client connects to. Any server
    ///   URLs defined in the OpenAPI document are available as static methods
    ///   on the ``Servers`` type.
    ///   - configuration: A set of configuration values for the client.
    ///   - transport: A transport that performs HTTP operations.
    ///   - middlewares: A list of middlewares to call before the transport.
    public init(
        serverURL: Foundation.URL,
        configuration: Configuration = .init(),
        transport: any ClientTransport,
        middlewares: [any ClientMiddleware] = []
    ) {
        self.client = .init(
            serverURL: serverURL,
            configuration: configuration,
            transport: transport,
            middlewares: middlewares
        )
    }
    private var converter: Converter {
        client.converter
    }
    /// - Remark: HTTP `GET /native/v1/server/public`.
    /// - Remark: Generated from `#/paths//native/v1/server/public/get`.
    public func getNativeV1ServerPublic(_ input: Operations.GetNativeV1ServerPublic.Input) async throws -> Operations.GetNativeV1ServerPublic.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1ServerPublic.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/server/public",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetNativeV1ServerPublic.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.NativeServerBootstrap.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/server`.
    /// - Remark: Generated from `#/paths//native/v1/server/get`.
    public func getNativeV1Server(_ input: Operations.GetNativeV1Server.Input) async throws -> Operations.GetNativeV1Server.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1Server.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/server",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetNativeV1Server.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.NativeServerDescription.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/media/{mediaSourceId}`.
    /// - Remark: Generated from `#/paths//native/v1/media/{mediaSourceId}/get`.
    public func getNativeV1MediaMediaSourceId(_ input: Operations.GetNativeV1MediaMediaSourceId.Input) async throws -> Operations.GetNativeV1MediaMediaSourceId.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1MediaMediaSourceId.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/media/{}",
                    parameters: [
                        input.path.mediaSourceId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "token",
                    value: input.query.token
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    return .ok(.init())
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `HEAD /native/v1/media/{mediaSourceId}`.
    /// - Remark: Generated from `#/paths//native/v1/media/{mediaSourceId}/head`.
    public func headNativeV1MediaMediaSourceId(_ input: Operations.HeadNativeV1MediaMediaSourceId.Input) async throws -> Operations.HeadNativeV1MediaMediaSourceId.Output {
        try await client.send(
            input: input,
            forOperation: Operations.HeadNativeV1MediaMediaSourceId.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/media/{}",
                    parameters: [
                        input.path.mediaSourceId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .head
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "token",
                    value: input.query.token
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    return .ok(.init())
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/media/{mediaSourceId}/remux`.
    /// - Remark: Generated from `#/paths//native/v1/media/{mediaSourceId}/remux/get`.
    public func getNativeV1MediaMediaSourceIdRemux(_ input: Operations.GetNativeV1MediaMediaSourceIdRemux.Input) async throws -> Operations.GetNativeV1MediaMediaSourceIdRemux.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1MediaMediaSourceIdRemux.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/media/{}/remux",
                    parameters: [
                        input.path.mediaSourceId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "token",
                    value: input.query.token
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "audioStreamId",
                    value: input.query.audioStreamId
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "subtitleStreamId",
                    value: input.query.subtitleStreamId
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "signalling",
                    value: input.query.signalling
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    return .ok(.init())
                case 404:
                    return .notFound(.init())
                case 503:
                    return .serviceUnavailable(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `HEAD /native/v1/media/{mediaSourceId}/remux`.
    /// - Remark: Generated from `#/paths//native/v1/media/{mediaSourceId}/remux/head`.
    public func headNativeV1MediaMediaSourceIdRemux(_ input: Operations.HeadNativeV1MediaMediaSourceIdRemux.Input) async throws -> Operations.HeadNativeV1MediaMediaSourceIdRemux.Output {
        try await client.send(
            input: input,
            forOperation: Operations.HeadNativeV1MediaMediaSourceIdRemux.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/media/{}/remux",
                    parameters: [
                        input.path.mediaSourceId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .head
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "token",
                    value: input.query.token
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "audioStreamId",
                    value: input.query.audioStreamId
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "subtitleStreamId",
                    value: input.query.subtitleStreamId
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "signalling",
                    value: input.query.signalling
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    return .ok(.init())
                case 404:
                    return .notFound(.init())
                case 503:
                    return .serviceUnavailable(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/media/{mediaSourceId}/tracks/{streamId}`.
    /// - Remark: Generated from `#/paths//native/v1/media/{mediaSourceId}/tracks/{streamId}/get`.
    public func getNativeV1MediaMediaSourceIdTracksStreamId(_ input: Operations.GetNativeV1MediaMediaSourceIdTracksStreamId.Input) async throws -> Operations.GetNativeV1MediaMediaSourceIdTracksStreamId.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1MediaMediaSourceIdTracksStreamId.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/media/{}/tracks/{}",
                    parameters: [
                        input.path.mediaSourceId,
                        input.path.streamId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "token",
                    value: input.query.token
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    return .ok(.init())
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `HEAD /native/v1/media/{mediaSourceId}/tracks/{streamId}`.
    /// - Remark: Generated from `#/paths//native/v1/media/{mediaSourceId}/tracks/{streamId}/head`.
    public func headNativeV1MediaMediaSourceIdTracksStreamId(_ input: Operations.HeadNativeV1MediaMediaSourceIdTracksStreamId.Input) async throws -> Operations.HeadNativeV1MediaMediaSourceIdTracksStreamId.Output {
        try await client.send(
            input: input,
            forOperation: Operations.HeadNativeV1MediaMediaSourceIdTracksStreamId.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/media/{}/tracks/{}",
                    parameters: [
                        input.path.mediaSourceId,
                        input.path.streamId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .head
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "token",
                    value: input.query.token
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    return .ok(.init())
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/items/{id}/images/{imageType}`.
    /// - Remark: Generated from `#/paths//native/v1/items/{id}/images/{imageType}/get`.
    public func getNativeV1ItemsIdImagesImageType(_ input: Operations.GetNativeV1ItemsIdImagesImageType.Input) async throws -> Operations.GetNativeV1ItemsIdImagesImageType.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1ItemsIdImagesImageType.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/items/{}/images/{}",
                    parameters: [
                        input.path.id,
                        input.path.imageType
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "tag",
                    value: input.query.tag
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "index",
                    value: input.query.index
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    return .ok(.init())
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/recommendations`.
    /// - Remark: Generated from `#/paths//native/v1/recommendations/get`.
    public func getNativeV1Recommendations(_ input: Operations.GetNativeV1Recommendations.Input) async throws -> Operations.GetNativeV1Recommendations.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1Recommendations.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/recommendations",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "kind",
                    value: input.query.kind
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "limit",
                    value: input.query.limit
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetNativeV1Recommendations.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.RecommendationFeedDto.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/watchlist`.
    /// - Remark: Generated from `#/paths//native/v1/watchlist/get`.
    public func getNativeV1Watchlist(_ input: Operations.GetNativeV1Watchlist.Input) async throws -> Operations.GetNativeV1Watchlist.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1Watchlist.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/watchlist",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetNativeV1Watchlist.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            [Components.Schemas.WatchlistItemDto].self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/releases/calendar`.
    /// - Remark: Generated from `#/paths//native/v1/releases/calendar/get`.
    public func getNativeV1ReleasesCalendar(_ input: Operations.GetNativeV1ReleasesCalendar.Input) async throws -> Operations.GetNativeV1ReleasesCalendar.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1ReleasesCalendar.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/releases/calendar",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "from",
                    value: input.query.from
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "to",
                    value: input.query.to
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetNativeV1ReleasesCalendar.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            [Components.Schemas.CalendarEventDto].self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/reminders`.
    /// - Remark: Generated from `#/paths//native/v1/reminders/get`.
    public func getNativeV1Reminders(_ input: Operations.GetNativeV1Reminders.Input) async throws -> Operations.GetNativeV1Reminders.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1Reminders.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/reminders",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetNativeV1Reminders.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            [Components.Schemas.ReminderDto].self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/people/{provider}/{providerId}`.
    /// - Remark: Generated from `#/paths//native/v1/people/{provider}/{providerId}/get`.
    public func getNativeV1PeopleProviderProviderId(_ input: Operations.GetNativeV1PeopleProviderProviderId.Input) async throws -> Operations.GetNativeV1PeopleProviderProviderId.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1PeopleProviderProviderId.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/people/{}/{}",
                    parameters: [
                        input.path.provider,
                        input.path.providerId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetNativeV1PeopleProviderProviderId.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.PersonDetailDto.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/history/calendar`.
    /// - Remark: Generated from `#/paths//native/v1/history/calendar/get`.
    public func getNativeV1HistoryCalendar(_ input: Operations.GetNativeV1HistoryCalendar.Input) async throws -> Operations.GetNativeV1HistoryCalendar.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1HistoryCalendar.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/history/calendar",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "from",
                    value: input.query.from
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "toExclusive",
                    value: input.query.toExclusive
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetNativeV1HistoryCalendar.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.WatchHistoryCalendarResponse.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/history/calendar/undated`.
    /// - Remark: Generated from `#/paths//native/v1/history/calendar/undated/get`.
    public func getNativeV1HistoryCalendarUndated(_ input: Operations.GetNativeV1HistoryCalendarUndated.Input) async throws -> Operations.GetNativeV1HistoryCalendarUndated.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1HistoryCalendarUndated.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/history/calendar/undated",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "kind",
                    value: input.query.kind
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetNativeV1HistoryCalendarUndated.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.WatchHistoryUndatedPage.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/events`.
    /// - Remark: Generated from `#/paths//native/v1/events/get`.
    public func getNativeV1Events(_ input: Operations.GetNativeV1Events.Input) async throws -> Operations.GetNativeV1Events.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1Events.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/events",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    return .ok(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/items/{id}`.
    /// - Remark: Generated from `#/paths//native/v1/items/{id}/get`.
    public func getNativeV1ItemsId(_ input: Operations.GetNativeV1ItemsId.Input) async throws -> Operations.GetNativeV1ItemsId.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1ItemsId.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/items/{}",
                    parameters: [
                        input.path.id
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetNativeV1ItemsId.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.NativeItemDto.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /native/v1/playback/resolve`.
    /// - Remark: Generated from `#/paths//native/v1/playback/resolve/post`.
    public func postNativeV1PlaybackResolve(_ input: Operations.PostNativeV1PlaybackResolve.Input) async throws -> Operations.PostNativeV1PlaybackResolve.Output {
        try await client.send(
            input: input,
            forOperation: Operations.PostNativeV1PlaybackResolve.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/playback/resolve",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.PostNativeV1PlaybackResolve.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.NativePlaybackResolutionResponse.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /native/v1/playback/sessions/start`.
    /// - Remark: Generated from `#/paths//native/v1/playback/sessions/start/post`.
    public func postNativeV1PlaybackSessionsStart(_ input: Operations.PostNativeV1PlaybackSessionsStart.Input) async throws -> Operations.PostNativeV1PlaybackSessionsStart.Output {
        try await client.send(
            input: input,
            forOperation: Operations.PostNativeV1PlaybackSessionsStart.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/playback/sessions/start",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.PostNativeV1PlaybackSessionsStart.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.NativeSessionStarted.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /native/v1/playback/sessions/progress`.
    /// - Remark: Generated from `#/paths//native/v1/playback/sessions/progress/post`.
    public func postNativeV1PlaybackSessionsProgress(_ input: Operations.PostNativeV1PlaybackSessionsProgress.Input) async throws -> Operations.PostNativeV1PlaybackSessionsProgress.Output {
        try await client.send(
            input: input,
            forOperation: Operations.PostNativeV1PlaybackSessionsProgress.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/playback/sessions/progress",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 204:
                    return .noContent(.init())
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /native/v1/playback/sessions/stop`.
    /// - Remark: Generated from `#/paths//native/v1/playback/sessions/stop/post`.
    public func postNativeV1PlaybackSessionsStop(_ input: Operations.PostNativeV1PlaybackSessionsStop.Input) async throws -> Operations.PostNativeV1PlaybackSessionsStop.Output {
        try await client.send(
            input: input,
            forOperation: Operations.PostNativeV1PlaybackSessionsStop.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/playback/sessions/stop",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 204:
                    return .noContent(.init())
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/playback/preferences`.
    /// - Remark: Generated from `#/paths//native/v1/playback/preferences/get`.
    public func getNativeV1PlaybackPreferences(_ input: Operations.GetNativeV1PlaybackPreferences.Input) async throws -> Operations.GetNativeV1PlaybackPreferences.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1PlaybackPreferences.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/playback/preferences",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetNativeV1PlaybackPreferences.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            [Components.Schemas.NativePreferenceDto].self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `PUT /native/v1/playback/preferences`.
    /// - Remark: Generated from `#/paths//native/v1/playback/preferences/put`.
    public func putNativeV1PlaybackPreferences(_ input: Operations.PutNativeV1PlaybackPreferences.Input) async throws -> Operations.PutNativeV1PlaybackPreferences.Output {
        try await client.send(
            input: input,
            forOperation: Operations.PutNativeV1PlaybackPreferences.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/playback/preferences",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .put
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.PutNativeV1PlaybackPreferences.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.NativePreferenceDto.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `DELETE /native/v1/playback/preferences`.
    /// - Remark: Generated from `#/paths//native/v1/playback/preferences/delete`.
    public func deleteNativeV1PlaybackPreferences(_ input: Operations.DeleteNativeV1PlaybackPreferences.Input) async throws -> Operations.DeleteNativeV1PlaybackPreferences.Output {
        try await client.send(
            input: input,
            forOperation: Operations.DeleteNativeV1PlaybackPreferences.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/playback/preferences",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .delete
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "mediaItemId",
                    value: input.query.mediaItemId
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 204:
                    return .noContent(.init())
                case 404:
                    return .notFound(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /native/v1/sync`.
    /// - Remark: Generated from `#/paths//native/v1/sync/get`.
    public func getNativeV1Sync(_ input: Operations.GetNativeV1Sync.Input) async throws -> Operations.GetNativeV1Sync.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetNativeV1Sync.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/native/v1/sync",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "cursor",
                    value: input.query.cursor
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetNativeV1Sync.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.NativeSyncPage.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
}
