// <auto-generated />
using System;
using MediaServer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaServer.Api.Data.Migrations
{
    [DbContext(typeof(MediaServerDbContext))]
    [Migration("20260714155630_AddReleaseTracking")]
    partial class AddReleaseTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MediaServer.Api.Data.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomReleaseGroups")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("MediaServer.Api.Data.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("HostUserId")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("MediaServer.Api.Data.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultKeepSeeding")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LowDiskSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamingTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfflineSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("Root")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Root")
                        .IsUnique();

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("MediaServer.Api.Data.Download", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("KeepSeeding")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUri")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("InfoHash")
                        .IsUnique();

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("MediaServer.Api.Data.ImageAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("ImageAssets");
                });

            modelBuilder.Entity("MediaServer.Api.Data.IngestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseUntil")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewCandidates")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StagesCompleted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("DownloadId");

                    b.HasIndex("Status");

                    b.ToTable("IngestItems");
                });

            modelBuilder.Entity("MediaServer.Api.Data.JellyfinAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Revoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CredentialId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("JellyfinAccessTokens");
                });

            modelBuilder.Entity("MediaServer.Api.Data.JellyfinCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PermanentlyLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Revoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("JellyfinCredentials");
                });

            modelBuilder.Entity("MediaServer.Api.Data.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RelatedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedType")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelatedType", "RelatedId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultSourceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdentityEpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentityProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityProviderId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdentitySeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IndexNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IndexNumberEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentIndexNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Providers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("CatalogId", "IdentityProvider", "IdentityProviderId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MediaItemPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Character")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Job")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("PersonId");

                    b.ToTable("MediaItemPersons");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MediaSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("MediaSources");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MediaStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FrameRate")
                        .HasColumnType("REAL");

                    b.Property<string>("HdrFormat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsForced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StreamType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaSourceId");

                    b.ToTable("MediaStreams");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MetadataRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cast")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CommunityRating")
                        .HasColumnType("REAL");

                    b.Property<string>("Crew")
                        .HasColumnType("TEXT");

                    b.Property<string>("FetchedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Raw")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RuntimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tagline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "Provider", "Language")
                        .IsUnique();

                    b.ToTable("MetadataRecords");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MovieCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackdropUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderId")
                        .IsUnique();

                    b.ToTable("MovieCollections");
                });

            modelBuilder.Entity("MediaServer.Api.Data.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Biography")
                        .HasColumnType("TEXT");

                    b.Property<string>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deathday")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KnownForDepartment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderId")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("MediaServer.Api.Data.ReleaseReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeadDays")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("NotifyAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrackedTitleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackedTitleId");

                    b.HasIndex("AppUserId", "TrackedTitleId", "ReleaseType")
                        .IsUnique();

                    b.ToTable("ReleaseReminders");
                });

            modelBuilder.Entity("MediaServer.Api.Data.ReminderDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SentAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackedReleaseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackedReleaseId");

                    b.HasIndex("ReminderId", "TrackedReleaseId")
                        .IsUnique();

                    b.ToTable("ReminderDeliveries");
                });

            modelBuilder.Entity("MediaServer.Api.Data.SourceFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignmentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edition")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngestItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TorrentFileIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("IngestItemId", "RelativePath")
                        .IsUnique();

                    b.ToTable("SourceFiles");
                });

            modelBuilder.Entity("MediaServer.Api.Data.TrackedRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RawType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrackedTitleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("TrackedTitleId", "Region", "Type", "Season", "Episode")
                        .IsUnique();

                    b.ToTable("TrackedReleases");
                });

            modelBuilder.Entity("MediaServer.Api.Data.TrackedTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductionStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Providers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("IdentityProvider", "IdentityProviderId")
                        .IsUnique();

                    b.ToTable("TrackedTitles");
                });

            modelBuilder.Entity("MediaServer.Api.Data.TranscodeJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Crf")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngineJobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("HardwareAcceleration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PercentComplete")
                        .HasColumnType("REAL");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("EngineJobId")
                        .IsUnique();

                    b.HasIndex("MediaItemId");

                    b.HasIndex("MediaSourceId");

                    b.HasIndex("State");

                    b.ToTable("TranscodeJobs");
                });

            modelBuilder.Entity("MediaServer.Api.Data.UserItemData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastPlayedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlaybackPositionTicks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Played")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("AppUserId", "MediaItemId")
                        .IsUnique();

                    b.ToTable("UserItemData");
                });

            modelBuilder.Entity("MediaServer.Api.Data.WatchlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MonitorScope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonitoredSeasons")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionOverride")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackedTitleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackedTitleId");

                    b.HasIndex("AppUserId", "TrackedTitleId")
                        .IsUnique();

                    b.ToTable("WatchlistEntries");
                });

            modelBuilder.Entity("MediaServer.Api.Data.Download", b =>
                {
                    b.HasOne("MediaServer.Api.Data.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("MediaServer.Api.Data.ImageAsset", b =>
                {
                    b.HasOne("MediaServer.Api.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("MediaServer.Api.Data.IngestItem", b =>
                {
                    b.HasOne("MediaServer.Api.Data.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaServer.Api.Data.Download", "Download")
                        .WithMany()
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Catalog");

                    b.Navigation("Download");
                });

            modelBuilder.Entity("MediaServer.Api.Data.JellyfinAccessToken", b =>
                {
                    b.HasOne("MediaServer.Api.Data.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaServer.Api.Data.JellyfinCredential", "Credential")
                        .WithMany("Tokens")
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("MediaServer.Api.Data.JellyfinCredential", b =>
                {
                    b.HasOne("MediaServer.Api.Data.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MediaItem", b =>
                {
                    b.HasOne("MediaServer.Api.Data.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaServer.Api.Data.MovieCollection", "Collection")
                        .WithMany("Movies")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediaServer.Api.Data.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Catalog");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MediaItemPerson", b =>
                {
                    b.HasOne("MediaServer.Api.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaServer.Api.Data.Person", "Person")
                        .WithMany("Credits")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MediaSource", b =>
                {
                    b.HasOne("MediaServer.Api.Data.MediaItem", "MediaItem")
                        .WithMany("Sources")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MediaStream", b =>
                {
                    b.HasOne("MediaServer.Api.Data.MediaSource", "MediaSource")
                        .WithMany("Streams")
                        .HasForeignKey("MediaSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaSource");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MetadataRecord", b =>
                {
                    b.HasOne("MediaServer.Api.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("MediaServer.Api.Data.ReleaseReminder", b =>
                {
                    b.HasOne("MediaServer.Api.Data.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaServer.Api.Data.TrackedTitle", "TrackedTitle")
                        .WithMany()
                        .HasForeignKey("TrackedTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("TrackedTitle");
                });

            modelBuilder.Entity("MediaServer.Api.Data.ReminderDelivery", b =>
                {
                    b.HasOne("MediaServer.Api.Data.ReleaseReminder", "Reminder")
                        .WithMany("Deliveries")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaServer.Api.Data.TrackedRelease", "TrackedRelease")
                        .WithMany()
                        .HasForeignKey("TrackedReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");

                    b.Navigation("TrackedRelease");
                });

            modelBuilder.Entity("MediaServer.Api.Data.SourceFile", b =>
                {
                    b.HasOne("MediaServer.Api.Data.Download", "Download")
                        .WithMany("SourceFiles")
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediaServer.Api.Data.IngestItem", "IngestItem")
                        .WithMany("SourceFiles")
                        .HasForeignKey("IngestItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaServer.Api.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Download");

                    b.Navigation("IngestItem");

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("MediaServer.Api.Data.TrackedRelease", b =>
                {
                    b.HasOne("MediaServer.Api.Data.TrackedTitle", "TrackedTitle")
                        .WithMany("Releases")
                        .HasForeignKey("TrackedTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedTitle");
                });

            modelBuilder.Entity("MediaServer.Api.Data.TrackedTitle", b =>
                {
                    b.HasOne("MediaServer.Api.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("MediaServer.Api.Data.TranscodeJob", b =>
                {
                    b.HasOne("MediaServer.Api.Data.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaServer.Api.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaServer.Api.Data.MediaSource", "MediaSource")
                        .WithMany()
                        .HasForeignKey("MediaSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("MediaItem");

                    b.Navigation("MediaSource");
                });

            modelBuilder.Entity("MediaServer.Api.Data.UserItemData", b =>
                {
                    b.HasOne("MediaServer.Api.Data.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaServer.Api.Data.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("MediaServer.Api.Data.WatchlistEntry", b =>
                {
                    b.HasOne("MediaServer.Api.Data.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaServer.Api.Data.TrackedTitle", "TrackedTitle")
                        .WithMany("Entries")
                        .HasForeignKey("TrackedTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("TrackedTitle");
                });

            modelBuilder.Entity("MediaServer.Api.Data.Download", b =>
                {
                    b.Navigation("SourceFiles");
                });

            modelBuilder.Entity("MediaServer.Api.Data.IngestItem", b =>
                {
                    b.Navigation("SourceFiles");
                });

            modelBuilder.Entity("MediaServer.Api.Data.JellyfinCredential", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MediaItem", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MediaSource", b =>
                {
                    b.Navigation("Streams");
                });

            modelBuilder.Entity("MediaServer.Api.Data.MovieCollection", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MediaServer.Api.Data.Person", b =>
                {
                    b.Navigation("Credits");
                });

            modelBuilder.Entity("MediaServer.Api.Data.ReleaseReminder", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("MediaServer.Api.Data.TrackedTitle", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
